### ISSUE TITLE
TOC needs to generate left justified

### ISSUE THREAD

**Issue by RickStrahl** [DVaughan/TocGeneratorAddin#1]
I like the fact that this addin adds the TOC using only items that follow the current location of the TOC injection showing only what follows and ignoring anything before.

However, if add my TOC after an initial H1 element the the list will generate with indentation which causes it to not render as a list any longer:

![image](https://user-images.githubusercontent.com/1374013/28291305-bf5be1b0-6afe-11e7-9f76-4158e6eef54b.png)

When generated the TOC text looks like:

```md
[//]: # (TOC Begin)
	* [Features](#features)
	* [Why another Markdown Editor?](#why-another-markdown-editor?)
		* [Markdown Monster wants to eat your Markdown!](#markdown-monster-wants-to-eat-your-markdown!)
		* [Weblog Publishing](#weblog-publishing)
		* [Customizable](#customizable)
	* [Extensible with .NET Add-ins](#extensible-with-.net-add-ins)
		* [Markdown Monster Addin Registry](#markdown-monster-addin-registry)
	* [Provided Add-ins](#provided-add-ins)
		* [Other Add-ins - What do you want to build?](#other-add-ins---what-do-you-want-to-build?)
	* [Acknowledgements](#acknowledgements)
	* [Spread the Word about Markdown Monster](#spread-the-word-about-markdown-monster)
	* [License](#license)
	* [Warranty Disclaimer: No Warranty!](#warranty-disclaimer:-no-warranty!)

[//]: # (TOC End)
```

The first item is Features in the above and it's an H2 so it's indented with one tab.

I think the trick will be to generate the entire TOC and look for the minmum amount of whitespace used by any items and then trim it down from there.

I can see a few issues with the in place as a starting point too - if you start say with an H3 somewhere and then have H2 or H1 later in the document the list is likely to not render fully either. Not sure if there's a good work around to this except notifying the user.

**Comment by DVaughan** [comment]
I've just pushed an update that appears to resolve the issue.
The depth is now calculated relative to the first heading encountered.
A warning message is displayed if a heading has a lower depth than the first heading encountered.
